In [1]:
import numpy as np
import pandas as pd
from func import *

inf = np.inf
deg = np.deg2rad

# Nodos

In [2]:
# Coordenadas
# |x|y|
C = np.array([
    [0,0],
    [1,1],
    [4,9],
])
assert np.shape(C)[1] == 2

In [3]:
# Soportes
# |x|y|
S = np.array([
    [0,1],
    [0,1],
    [1,1]
])
assert np.shape(S) == np.shape(C)

# Barras

In [4]:
# Puntos
# |x|y|
P = np.array([
    [0,1],
    [1,2],
])
assert np.shape(P)[1] == 2, "Cada barra debe estar definida solo por 2 puntos."

In [5]:
# Longitudes
L = np.linalg.norm(np.diff(C[P], axis=1), axis=2)
L

array([[1.41421356],
       [8.54400375]])

In [6]:
# Ángulos directores
alpha = np.arctan(np.divide(*(np.diff(C[P], axis=1).squeeze().T[::-1])))
alpha

array([0.78539816, 1.21202566])

In [7]:
# Modulo de elasticidad - Area
# |E|A|
EA = np.array([
    [1, 2],
    [2, 2],
])
assert np.shape(EA)[1] == 2, "La matriz solo debe contener 2 valores por fila."
assert np.shape(EA)[0] == np.shape(P)[0], "No existe el número de barras."

In [8]:
stiffness_armor(1,1,1)

array([[ 1., -1.],
       [-1.,  1.]])

In [9]:
stiffness_beam(1,1,1)

NameError: name 'k' is not defined

In [ ]:
K = stiffness_2d(E=1+, 0A=1, I=2, L=1)
K

array([[  1.,   0.,   0.,  -1.,   0.,   0.],
       [ 12.,   6.,   0.,   0., -12.,   6.],
       [  6.,   4.,   0.,   0.,  -6.,   2.],
       [ -1.,   0.,   0.,   1.,   0.,   0.],
       [-12.,  -6.,   0.,   0.,  12.,  -6.],
       [  6.,   2.,   0.,   0.,  -6.,   4.]])

In [ ]:
K[I]

NameError: name 'I' is not defined

In [ ]:
B = stiffness_beam(1,1,1)

In [ ]:
B

array([[ 12.,   6., -12.,   6.],
       [  6.,   4.,  -6.,   2.],
       [-12.,  -6.,  12.,  -6.],
       [  6.,   2.,  -6.,   4.]])