In [6]:
import ipywidgets as widgets
from IPython.display import display

# Sample data for the table
data = [{'Name': 'Alice', 'Age': 30, 'City': 'New York'},
        {'Name': 'Bob', 'Age': 25, 'City': 'Los Angeles'},
        {'Name': 'Charlie', 'Age': 35, 'City': 'Chicago'}]

# Create a DataGrid widget
data_grid = widgets.DataGrid(editable=True, column_headers=True)
data_grid.header = ['Name', 'Age', 'City']
data_grid.rows = [[row['Name'], row['Age'], row['City']] for row in data]

# Function to handle changes in the table
def on_value_change(change):
    data_grid.update(change['new'])

data_grid.observe(on_value_change, 'values')

# Display the table
display(data_grid)


AttributeError: module 'ipywidgets' has no attribute 'DataGrid'

In [4]:
connections

[((1.0, 1.0), (2.0, 2.0)),
 ((1.0, 1.0), (2.0, 2.0)),
 ((1.0, 1.0), (2.0, 2.0)),
 ((1.0, 1.0), (2.0, 2.0))]

In [2]:
import numpy as np

In [18]:
a = np.diag([1,2,3,4,5])
a[2,3] = 5
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 5, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [25]:
ll = list([*a[~np.any(a == 5, axis=1)]])

In [26]:
ll

[array([1, 0, 0, 0, 0]), array([0, 2, 0, 0, 0]), array([0, 0, 0, 4, 0])]

In [15]:
np.any(a == 1, axis=1)

array([ True, False, False, False, False])

In [7]:
a[a == 1] += 1

In [8]:
a

array([[2, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])